/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "ExploitationDetector",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExploitationDetector__factory>;
    getContractFactory(
      name: "Payout",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Payout__factory>;
    getContractFactory(
      name: "PolicyMaker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolicyMaker__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "ExploitationDetector",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExploitationDetector>;
    getContractAt(
      name: "Payout",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Payout>;
    getContractAt(
      name: "PolicyMaker",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PolicyMaker>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
